TorneoWEB/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from torneo.views import RegistroUsuario
from django.conf.urls import url
from django.contrib.auth.views import LoginView,LogoutView

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('torneo/',include('torneo.urls')),
    url('registrar',RegistroUsuario.as_view(),name="registrar"),
    path('login/', LoginView.as_view(template_name="torneo/login.html"), name="login"),
    path('logout/', LogoutView.as_view(template_name="torneo/login.html"), name="logout"),
] 
urlpatterns += staticfiles_urlpatterns()

polls/urls.py
from django.urls import path

from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

torneo/urls.py
from django.urls import path

from . import views

app_name = "torneo"

urlpatterns = [

    path('equipo/',views.equipoCapitan,name='mostrarEquipo'),
    path('',views.home,name='home'),
    path('fotos',views.fotos,name="fotos"),
    path('posiciones/',views.posiciones,name="posiciones"),
    path('equipo/<int:integrante_id>/',views.integranteModificacion,name="ModificiacionIntegrante"),
    path('equipo/registroIntegrante',views.registroIntegrante,name="registroIntegrante"),
    path('inscripcion',views.inscripcionEquipo,name="InscripcionEquipo"),
    path('contactenos',views.contactenos,name="contactenos"),
    path('posiciones/historialTorneos',views.historialTorneos,name="historialTorneos"),
    #TERMINAR VER TABLERO
    path('equipo/empezarTorneo',views.empezarTorneo,name="empezarTorneo"),
    #TERMINAR VER TABLERO
    path('equipo/finalizarTorneo',views.finalizarTorneo,name="finalizarTorneo"),
    path('equipo/<int:integrante_id>/eliminar',views.eliminarIntegrante,name="EliminarIntegrante"),
    #path('<int:capitan_id>/',views.equipoCapitan,name='mostrarEquipo'),
    #path('<int:capitan_id>/',views.equipoCapitan,name='mostrarEquipo'),
    #path('',None,name='mostrarCaracteristicas'),
    #path('',None,name='inscribete'),
    #path('',None,name='configuraEquipo'),

]

torneo/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from datetime import datetime as tiempo

# Create your models here.


class Capitan(User):
    user = models.OneToOneField(User,on_delete=models.CASCADE,parent_link=True)
    tDocumentos = (("CC","Cedula Ciudadania"),("TI","Tarjeta Identidad"),("CE","Cedula Extranjeria"))
    tipoDocumento = models.CharField(max_length=2,choices=tDocumentos,default="CC")
    numeroDocumento = models.CharField(max_length=11,unique=True)
    carne = models.CharField(max_length=7,unique=True)
    tAfinacion = (("Pregrado","Pregrado"),("Posgrado","Posgrado"),("Graduado","Graduado"),("Profesor","Profesor"),("Personal Administrativo","Personal Administrativo"))
    afinacion = models.CharField(max_length=23,choices=tAfinacion,default="Pregrado")
    celular = models.CharField(max_length=10)
    semestre = models.CharField(max_length=2,null = True,blank=True) #solo es requerido si es pregrado
    semestreGrado = models.CharField(max_length=6,null = True,blank=True) #Para graduados EJ: 2019-2
    nombreEquipo = models.CharField(max_length=200, unique=True)
    
    def __str__(self):
        return self.user.username+" - "+ self.first_name +" "+ self.last_name+" - "+ self.nombreEquipo

class Integrante(models.Model):
    capitan = models.ForeignKey(Capitan, on_delete= models.CASCADE)
    nombreCompleto = models.CharField(max_length=200)
    apellidoCompleto = models.CharField(max_length=200)
    semestre = models.CharField(max_length=2,null=True,blank=True)
    carne = models.CharField(max_length=7,unique=True,blank=True)
    
    def __str__(self):
        return self.nombreCompleto+" "+self.apellidoCompleto
    
class Fase(models.Model):
    user = models.ForeignKey(Capitan, on_delete= models.CASCADE)
    tEtapas = (("Grupo","Grupo"),("Cuartos","Cuartos de Final"),("Semifinal","Semifinal"),("Final","Final"))
    tipoEtapas = models.CharField(max_length=10,choices=tEtapas,default="Grupo")
    tGrupos = (("A","A"),("B","B"),("C","C"),("D","D"),("E","E"))
    tipoGrupos = models.CharField(max_length=1,choices=tGrupos,default="A",null=True,blank=True)

    def __str__(self):
        return self.user.nombreEquipo+" - "+self.tipoEtapas

class Torneo(models.Model):
    tiempoActual = tiempo.now()
    if tiempoActual.month <5:
        semestre = 1
    elif tiempoActual.month > 7:
        semestre = 2
    else:
        semestre = "I"
    nuevaCadena = str(tiempoActual.year)+"-"+str(semestre)
    nombre = models.CharField(max_length=6,default=nuevaCadena,editable=False,unique=True)
    fechaInicio = models.DateField(auto_now_add=True,editable=False)
    fechaFin = models.DateField(null=True,blank=True)
    primerPuesto = models.ForeignKey(Capitan, on_delete= models.CASCADE,related_name='primerPuesto',null=True,blank=True)
    segundoPuesto = models.ForeignKey(Capitan, on_delete= models.CASCADE,related_name='segundoPuesto',null=True,blank=True)
    tercerPuesto = models.ForeignKey(Capitan, on_delete= models.CASCADE,related_name='tercerPuesto',null=True,blank=True)


    def __str__(self):
        return self.nombre

torneo/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import HttpResponse
import django


# Create your views here.
from django.shortcuts import get_object_or_404, render
from .models import Capitan,Integrante,Fase,Torneo
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy
from torneo.registroForm import RegistroForm,RegistroIntegrante,FinalizarTorneo
from django.contrib.auth.decorators import login_required
from random import randint
from datetime import datetime as tiempo
from django.core.exceptions import ObjectDoesNotExist


@login_required
def equipoCapitan(request):
    
    if request.user.is_superuser:
        nuevaCadena = nombreTorneo()
        try:
            torneo = Torneo.objects.get(nombre=nuevaCadena)
        except ObjectDoesNotExist:
            torneo = None
        return render(request,'torneo/panelAdministracion.html',{"torneo":torneo})
    else: 
        capitan = get_object_or_404(Capitan, pk=request.user.pk)
        faseDeGrupos = len(Fase.objects.filter(user__exact=capitan,tipoEtapas__exact="Grupo"))
        return render(request,'torneo/equipoCapitan.html',{'capitan':capitan,'fase':faseDeGrupos})
   
def fotos(request):
    return HttpResponse("Estamos en consutruccion")

def historialTorneos(request):
    torneos = Torneo.objects.exclude(fechaFin__isnull=True)

    return render(request,'torneo/historialTorneos.html',{'torneos':torneos})

@login_required
def empezarTorneo(request):
    if request.user.is_staff:
        torneo = Torneo()
        torneo.save()
        return redirect("/torneo/equipo/")
    else:
        return HttpResponse("Ey no puedes hacer eso")

@login_required
def finalizarTorneo(request):
    if not(request.user.is_staff):
        return HttpResponse("Ey no puedes hacer eso")
    nuevaCadena = nombreTorneo()
    try:
        torneo = Torneo.objects.get(nombre=nuevaCadena)
        equiposInscritos = Fase.objects.all().delete()
        
        if request.method == 'POST':
            form = FinalizarTorneo(request.POST,instance=torneo)
            if form.is_valid():
                formulario = form.save(commit=False)
                torneo.fechaFin = django.utils.timezone.now()
                formulario.save()
                return redirect("/torneo/equipo")
        else:
            form = FinalizarTorneo()

        return render(request, 'torneo/finalizarTorneo.html', {'form': form,'torneo':torneo}) 
    except ObjectDoesNotExist:
        return HttpResponse("Estamos en consutruccion")
    

def posiciones(request):
    grupoA = Fase.objects.filter(tipoGrupos__exact="A",tipoEtapas__exact="Grupo")
    grupoB = Fase.objects.filter(tipoGrupos__exact="B",tipoEtapas__exact="Grupo")
    grupoC = Fase.objects.filter(tipoGrupos__exact="C",tipoEtapas__exact="Grupo")
    grupoD = Fase.objects.filter(tipoGrupos__exact="D",tipoEtapas__exact="Grupo")
    grupoE = Fase.objects.filter(tipoGrupos__exact="E",tipoEtapas__exact="Grupo")
    matriz = []
    for i in range(4):
        if i>=len(grupoA):
            A = None
        else:
            A = grupoA[i]
        if i>=len(grupoB):
            B = None
        else:
            B = grupoB[i]
        if i>=len(grupoC):
            C = None
        else:
            C = grupoC[i]
        if i>=len(grupoD):
            D = None
        else:
            D = grupoD[i]
        if i>=len(grupoE):
            E = None
        else:
            E = grupoE[i]
        matriz += [[A,B,C,D,E]]

    return render(request,'torneo/posiciones.html',{'range':range(5),'matriz':matriz})

def contactenos(request):
    return HttpResponse("Estamos en consutruccion")
    
def eliminarIntegrante(request,integrante_id):
    integrante = get_object_or_404(Integrante,pk=integrante_id)
    integrante.delete()
    capitan = get_object_or_404(Capitan, pk=request.user.pk)
    return redirect("/torneo/equipo")

def integranteModificacion(request,integrante_id):
    capitan = get_object_or_404(Capitan, pk=request.user.pk)
    integrante = Integrante.objects.filter(pk=integrante_id)
    if integrante[0].capitan != capitan:
        return HttpResponse("Ey no puedes hacer eso")


    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        integrante = Integrante.objects.filter(capitan=capitan,pk=integrante_id)
        form = RegistroIntegrante(request.POST,instance=integrante[0])
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            formulario = form.save(commit=False)
            formulario.save()
            # redirect to a new URL:
            return redirect("/torneo/equipo")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RegistroIntegrante()

    return render(request, 'torneo/modificarIntegrante.html', {'form': form,'integrante':integrante[0]})


@login_required
def inscripcionEquipo(request):
    capitan = get_object_or_404(Capitan, pk=request.user.pk)
    #flag permite comprobar si el usuario puede inscribir el equipo o no.
    flag = True
    try:
        torneo = Torneo.objects.get(nombre=nombreTorneo(),fechaFin=None)
    except ObjectDoesNotExist:
        flag = False
        return HttpResponse("No hay torneo activo, intenta despues")

    if len(Integrante.objects.filter(capitan=request.user))<7 and len(Integrante.objects.filter(capitan=request.user))>10:
        flag = False
        return HttpResponse("Tienes que tener registrados de 7 a 10 integrantes")


    if len(Fase.objects.filter(tipoEtapas__exact="Grupo")) >= 20:
        flag = False
    for i in Fase.objects.all():
        if i.user == capitan:
            flag = False
            break
    grupoA = Fase.objects.filter(tipoGrupos__exact="A",tipoEtapas__exact="Grupo")
    grupoB = Fase.objects.filter(tipoGrupos__exact="B",tipoEtapas__exact="Grupo")
    grupoC = Fase.objects.filter(tipoGrupos__exact="C",tipoEtapas__exact="Grupo")
    grupoD = Fase.objects.filter(tipoGrupos__exact="D",tipoEtapas__exact="Grupo")
    grupoE = Fase.objects.filter(tipoGrupos__exact="E",tipoEtapas__exact="Grupo")
    tipos = [(grupoA,"A"),(grupoB,"B"),(grupoC,"C"),(grupoD,"D"),(grupoE,"E")]
    while flag:
        actual = tipos[randint(0,4)]
        if 0<=len(actual[0]) and len(actual[0])<5:
            flag = False
            superFase = Fase(user=capitan,tipoEtapas="Grupo",tipoGrupos=actual[1])
            superFase.save()
    return redirect("/torneo/equipo")

 


def home(request):
    return render(request,'torneo/index.html')

@login_required
def registroIntegrante(request):
    capitan = get_object_or_404(Capitan, pk=request.user.pk)
    integrantes = Integrante.objects.filter(capitan=capitan)
    if len(integrantes) == 10:
        #Colocar un render a un error de que ya tiene 11 miembros en su equipo
        return render(request,'torneo/equipoCapitan.html',{'capitan':capitan})

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegistroIntegrante(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            formulario = form.save(commit=False)
            capitan = get_object_or_404(Capitan, pk=request.user.pk)
            formulario.capitan = capitan
            formulario.save()
            # redirect to a new URL:
            return redirect("/torneo/equipo")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RegistroIntegrante()

    return render(request, 'torneo/registroIntegrante.html', {'form': form})
    
class RegistroUsuario(CreateView):
    model = Capitan
    template_name = "torneo/registrar.html"
    form_class = RegistroForm
    success_url = "/torneo"

def nombreTorneo():
    tiempoActual = tiempo.now()
    if tiempoActual.month <5:
        semestre = 1
    elif tiempoActual.month > 7:
        semestre = 2
    else:
        semestre = "I"
    nuevaCadena = str(tiempoActual.year)+"-"+str(semestre)
    return nuevaCadena

torneo/templates/torneo/equipoCapitan.html
{% extends "torneo/index.html" %}
{% load torneo_extras %}

{% block content %}
{% if fase == 1 %}
<h3 style="width:100%;background-color:green;color:white">Ya te encuentras inscrito en el torneo actual</h3>
{% else %}
<h3 style="width:100%;background-color:green;color:red">NO te encuentras inscrito en el torneo actual</h3>
{% endif %}
<table style="width:100%;background-color:green">
<th><h1>{{ capitan.nombreEquipo }}</h1></th>

{%for integrante in capitan.integrante_set.all%}
<tr>
	<h4><th><a href={{"/torneo/equipo/"|addstr:integrante.pk}}>{{integrante.nombreCompleto}} {{integrante.apellidoCompleto}}</a></th></h4>
</tr>
{% endfor %}

</table>

<table style="width:100%;background-color:green">
	<tr>
		<th><a href ="registroIntegrante">Adicionar Integrante</a></th>
		<th><a href ="/torneo/inscripcion">Inscribir Equipo</a></th>
	</tr>
	
</table>

{% endblock %}

torneo/templates/torneo/finalizarTorneo.html
{% extends 'torneo/index.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'torneo/estiloRegistro.css'%}">
<div class="registroForm">
<form method="post">
	{% csrf_token %}
	{{ form.as_p}}
	<button type="submit">Guardar</button>
</form>
</div>
{% endblock %}

torneo/templates/torneo/historialTorneos.html
{% extends "torneo/index.html" %}
{% block content %}
<h2>HISTORIAL DE TORNEOS</h2>

{% for torneo in torneos %}
<hr/>
<h3>{{ torneo.nombre }}</h3>
<h4><table style="width:100%">
<tr>

	<th>CAMPEON</th>
	<th>SUB-CAMPEON</th>
	<th>TERCER PUESTO</th>

</tr> 
<tr>

	<th>{{ torneo.primerPuesto.nombreEquipo }}</th>
	<th>{{ torneo.segundoPuesto.nombreEquipo }}</th>
	<th>{{ torneo.tercerPuesto.nombreEquipo }}</th>

</tr>
</table></h4>

{% endfor %}
{% endblock %}

torneo/templates/torneo/index.html
<!DOCTYPE html>
{% load static %}
<html leng="es">

<head>
<title>Torneo de Futbol</title>
<link rel="stylesheet" href="{% static 'torneo/estiloIndex.css'%}">
</head>
<body>
	<header>
	<img id = "imagenCabeceraUno" src="{% static 'torneo/images/imagenCabecera.png'%}">
	<h1 id="textoCabecera">Torneo de Futbol</h1>
	<img id = "imagenCabeceraDos" src="{% static 'torneo/images/imagenCabecera.png'%}">
	
	</header>

	<hr/>
	<nav>

			<a href="/torneo"><img id ="Home" src="{% static 'torneo/images/button_home.png'%}">
</a>


<p>
			<a href="/torneo/posiciones"><img id ="Posiciones" src="{% static 'torneo/images/button_posiciones.png'%}">
</a>
</p>

<p>
			<a href="/torneo/fotos"><img id ="Fotos" src="{% static 'torneo/images/button_fotos.png'%}">
</a>
</p>
<p>
			<a href="/torneo/equipo"><img id ="Equipo" src="{% static 'torneo/images/button_equipo.png'%}">
</a>
</p>
		
	</nav>
	<hr/>

	<section style="background-color:green;width:100%">
		<table style="background-color:green;width:100%">
		<tr>
			<th><article><p id="fechaActual">XX/XX/XXXX</p></article></th>
		<article>
		<p><th>
		{% if user.is_authenticated %}
	 		<h4>Bienvenid@ <b>{{ user.username }}</b>, <a href="/logout">logout</a></h4>
		{% else %}
			<h4>Bienvenido te toca hacer <a href="/login"> login</a>, si no tienes cuenta <a href="/registrar"> creala</a></h4>
		{% endif %}
		</th>
		</tr>
		</table>
		</p>
		</article>

		{% block content %}
		{% endblock %}
	</section>
	<hr/>
	<footer>
	<p><h4 id = "footerEscuela"> Desarrollada por: </h4>
	<ul>
	<li>Orlando Gelves</li>
	</ul></p>
	<p id= "footerEscuela">Escuela Colombiana de Ingenieria Julio Garavito</p>

	</footer>
{% block javascript %}
	<script src="{% static 'js/primerJavaScript.js' %}"></script>
	<script src="{% static 'js/menusJS.js'%}"></script>
{% endblock %}

</body>
</html>

torneo/templates/torneo/login.html
{% extends 'torneo/index.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'torneo/estiloRegistro.css'%}">
<form method="post">
	{% csrf_token %}
	<div class="row">
		<div class="col-md-6-md-offset-3">
			<div class="form-group">
				<label for="username">Nombre de usuario:</label>
				<input class="form-control" type="text" name="username">
			</div>
		</div>
	</div>
<div class="row">
		<div class="col-md-6-md-offset-3">
			<div class="form-group">
				<label for="username">Contrasena:</label>
				<input class="form-control" type="password" name="password">
			</div>
		</div>
	</div>
<div class="row">
		<div class="col-md-6-md-offset-3">
			<div class="form-group">
				<a href="#">Olvide la contrasena</a>
			</div>
		</div>
	</div>


	
	<button type="submit">Guardar</button>
</form>
{% endblock %}

torneo/templates/torneo/modificarIntegrante.html
{% extends "torneo/index.html" %}
{% block content %}
<h3><a href="eliminar">ELIMINAR INTEGRANTE</a></h3>
<form method="post">
    {% csrf_token %}
    <div class="row">
		<div class="col-md-6-md-offset-3">
			<div class="form-group">
				<label for="nombreCompleto">Nombre Completo:</label>
				<input class="form-control" type="text" name="nombreCompleto" value={{ integrante.nombreCompleto }}>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6-md-offset-3">
			<div class="form-group">
				<label for="apellidoCompleto">Apellido Completo:</label>
				<input class="form-control" type="text" name="apellidoCompleto" value={{ integrante.apellidoCompleto }}>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6-md-offset-3">
			<div class="form-group">
				<label for="semestre">Semestre:</label>
				<input class="form-control" type="text" name="semestre" value={{integrante.semestre}}>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6-md-offset-3">
			<div class="form-group">
				<label for="carne">Carne:</label>
				<input class="form-control" type="text" name="carne" value={{integrante.carne}}>
			</div>
		</div>
	</div>
    <input type="submit" value="Submit">
</form>
{% endblock %}

torneo/templates/torneo/panelAdministracion.html
{% extends "torneo/index.html" %}

{% block content %}

</table>

<table style="width:100%;background-color:green">
	<tr>
		<th>TORNEO ACTUAL</th>
		<th>{% if torneo == None %}
				<a href ="/torneo/equipo/empezarTorneo">Empezar Torneo</a>
			{% elif torneo.fechaFin != None %}
				<p> No puedes realizar ninguna accion hasta el proximo semestre</p>
			{% else %}
				<a href ="/torneo/equipo/finalizarTorneo">Finalizar Torneo</a>
			{% endif %}
		</th>
		
	</tr>
	
</table>
{% endblock %}

torneo/templates/torneo/posiciones.html
{% extends "torneo/index.html" %}

{% block content %}
<a href="historialTorneos" style="text-align:left"><h3>HISTORIAL DE TORNEOS</h3></a>
<h2 style="background-color:green">FASE DE GRUPOS</h2>
<table style="width:100%;background-color:green">
	<tr>
		<th>A</th>
		<th>B</th>
		<th>C</th>
		<th>D</th>
		<th>E</th>
	</tr>
	{% for i in matriz %}
	<tr>
		{% for i2 in i %}
			{% if i2 == None %}
				<th> No hay inscrito</th>
	    	{% else %}
	    		<th>{{ i2.user.nombreEquipo }}</th>
	    	{% endif %}
	    {% endfor %}
		    
	</tr>
		
	{% endfor %}
</table>
{% endblock %}

torneo/templates/torneo/registrar.html
{% extends 'torneo/index.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'torneo/estiloRegistro.css'%}">
<div class="registroForm">
<form method="post">
	{% csrf_token %}
	{{ form.as_p}}
	<button type="submit">Guardar</button>
</form>
</div>
{% endblock %}

torneo/templates/torneo/registroCapitan.html
{% load static %}
<link rel="stylesheet" href="{% static 'torneo/estiloRegistro.css'%}">
<div class="registroForm">
{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p}}
	<button type="submit">Guardar</button>
</form>
</div>
{% endblock %}

torneo/templates/torneo/registroIntegrante.html
{% extends "torneo/index.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock %}